[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
mollusk-svm = "0.1.5"
solana-sdk = "2.2.1"

[patch.crates-io]
solana-sbpf = { git = "https://github.com/serbangv/sbpf-profiler" }

[features]
test-sbf = []
